# Site Settings
title: Start Jekyll
email: xxx@gmail.com
description: >
  A guide to getting started with Jekyll.
baseurl: "/startjekyll"
url: "http://p5yb14d3.github.io"
tumblr_username: p5yb14d3
twitter_username: p5yb14d3
github_username: p5yb14d3
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM